### ISSUE TITLE
F# compiler fails with AccessViolationException when running on 5.0 runtime

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/toolset#2866] opened 2019-09-13 18:00 UTC
As part of merging the cli and toolset repos, I ran into an access violation with the F# compiler.  This appears to only happen if fsc is targeting .NET Core 5 instead of .NET Core 3.  For now I am going to keep fsc targeting .NET Core 3 with the merge.

@KevinRansom @cartermp 

Here is the error I hit

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FSharp.Compiler.NameResolution+Item.get_Tag()
   at FSharp.Compiler.TypeChecker+MakeAndPublishSimpleVals@1892.Invoke(System.Tuple`2<NameResolutionEnv,range>, System.Tuple`8<pos,Item,Item,Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<Typar,TType>>,ItemOccurence,DisplayEnv,NameResolutionEnv,System.Tuple`3<AccessorDomain,range,Boolean>>)
   at Microsoft.FSharp.Collections.SeqModule.Fold[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,System.__Canon>>, System.__Canon, System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at FSharp.Compiler.TypeChecker.MakeAndPublishSimpleVals$cont@1870(cenv, TcEnv, Microsoft.FSharp.Collections.FSharpMap`2<System.String,PrelimValScheme1>, Microsoft.FSharp.Core.Unit)
   at FSharp.Compiler.TypeChecker.TcIteratedLambdas(cenv, Boolean, TcEnv, TType, Microsoft.FSharp.Collections.FSharpSet`1<System.String>, SyntacticUnscopedTyparEnv, SynExpr)
   at FSharp.Compiler.TypeChecker.TcExprUndelayed(cenv, TType, TcEnv, SyntacticUnscopedTyparEnv, SynExpr)
   at FSharp.Compiler.TypeChecker.TcExpr(cenv, TType, TcEnv, SyntacticUnscopedTyparEnv, SynExpr)
   at FSharp.Compiler.TypeChecker.TcNormalizedBinding(DeclKind, cenv, TcEnv, SyntacticUnscopedTyparEnv, TType, Microsoft.FSharp.Core.FSharpOption`1<Val>, SafeInitData, Microsoft.FSharp.Collections.FSharpList`1<Typar>, ExplicitTyparInfo, NormalizedBinding)
   at FSharp.Compiler.TypeChecker.TcNonRecursiveBinding(DeclKind, cenv, TcEnv, SyntacticUnscopedTyparEnv, TType, SynBinding)
   at FSharp.Compiler.TypeChecker+TcLetBinding@11308.Invoke(SyntacticUnscopedTyparEnv, SynBinding)
   at Microsoft.FSharp.Primitives.Basics.List.mapFold[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,System.Tuple`2<System.__Canon,System.__Canon>>>, System.__Canon, Microsoft.FSharp.Collections.FSharpList`1<System.__Canon>)
   at FSharp.Compiler.TypeChecker.TcLetBinding(cenv, Boolean, TcEnv, ContainerInfo, DeclKind, SyntacticUnscopedTyparEnv, Microsoft.FSharp.Collections.FSharpList`1<SynBinding>, range, range)
   at FSharp.Compiler.TypeChecker.TcLetBindings(cenv, TcEnv, ContainerInfo, DeclKind, SyntacticUnscopedTyparEnv, Microsoft.FSharp.Collections.FSharpList`1<SynBinding>, range, range)
   at FSharp.Compiler.TypeChecker+TcModuleOrNamespaceElementNonMutRec@17300-1.Invoke(Microsoft.FSharp.Core.Unit)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+catch@902-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+catch@902-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+catch@902-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+catch@902-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule+bind@893-1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(CompilationThreadToken)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule.forceWhile[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](CompilationThreadToken, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Boolean>, Eventually`1<System.__Canon>)
   at FSharp.Compiler.AbstractIL.Internal.Library+EventuallyModule.force[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](CompilationThreadToken, Eventually`1<System.__Canon>)
   at FSharp.Compiler.CompileOps.TypeCheckOneInput(CompilationThreadToken, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Boolean>, TcConfig, TcImports, TcGlobals, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Collections.FSharpList`1<Ident>>, TcState, ParsedInput)
   at FSharp.Compiler.CompileOps+TypeCheckClosedInputSet@5589.Invoke(TcState, ParsedInput)
   at Microsoft.FSharp.Primitives.Basics.List.mapFoldToFreshConsTail[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Collections.FSharpList`1<System.__Canon>, FSharpFunc`3<System.__Canon,System.__Canon,System.Tuple`2<System.__Canon,System.__Canon>>, System.__Canon, Microsoft.FSharp.Collections.FSharpList`1<System.__Canon>)
   at Microsoft.FSharp.Primitives.Basics.List.mapFold[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,System.Tuple`2<System.__Canon,System.__Canon>>>, System.__Canon, Microsoft.FSharp.Collections.FSharpList`1<System.__Canon>)
   at Microsoft.FSharp.Collections.ListModule.MapFold[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,System.Tuple`2<System.__Canon,System.__Canon>>>, System.__Canon, Microsoft.FSharp.Collections.FSharpList`1<System.__Canon>)
   at FSharp.Compiler.CompileOps.TypeCheckClosedInputSet(CompilationThreadToken, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Boolean>, TcConfig, TcImports, TcGlobals, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Collections.FSharpList`1<Ident>>, TcState, Microsoft.FSharp.Collections.FSharpList`1<ParsedInput>)
   at FSharp.Compiler.Driver.TypeCheck(CompilationThreadToken, TcConfig, TcImports, TcGlobals, ErrorLogger, System.String, FSharp.Compiler.NiceNameGenerator, TcEnv, Microsoft.FSharp.Collections.FSharpList`1<ParsedInput>, Exiter)
   at FSharp.Compiler.Driver.main0[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.String[], Resolver, Boolean, ReduceMemoryFlag, CopyFSharpCoreFlag, Exiter, ErrorLoggerProvider, DisposablesTracker)
   at FSharp.Compiler.Driver.typecheckAndCompile(CompilationThreadToken, System.String[], Resolver, Boolean, ReduceMemoryFlag, CopyFSharpCoreFlag, Exiter, ErrorLoggerProvider, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<TcImports,Microsoft.FSharp.Core.Unit>>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`3<TcGlobals,System.String,ILModuleDef>,Microsoft.FSharp.Core.Unit>>)
   at FSharp.Compiler.Driver.mainCompile(CompilationThreadToken, System.String[], Resolver, Boolean, ReduceMemoryFlag, CopyFSharpCoreFlag, Exiter, ErrorLoggerProvider, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<TcImports,Microsoft.FSharp.Core.Unit>>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`3<TcGlobals,System.String,ILModuleDef>,Microsoft.FSharp.Core.Unit>>)
   at FSharp.Compiler.CommandLineMain+Driver.main(System.String[])
   at FSharp.Compiler.CommandLineMain.main(System.String[])
```

**Comment by nguerrera** [comment] 2019-10-24 03:43
Duplicate of https://github.com/dotnet/coreclr/issues/27275

**Closed by nguerrera** 2019-10-24 03:43 UTC
